### ISSUE TITLE
Slight problem when running application.

### ISSUE THREAD

**Issue by carlca** [FlKo/LazarusDockedDesktops#2]
Apple Mac Pro - MacOS Sierra 10.12.5
Lazarus 1.6.4
FPC 3.0.2

Hello, this is a really good package. I've just installed it on Lazarus 1.6.4 on the Apple Mac, and it looks very pretty indeed! I prefer to Hide the IDE Windows on run so I have that option checked. It doesn't appear to have any effect. Also, when I am running the application, the IDE window shifts up off the top of the screen by a few millimeters and I have to click the Lazarus Title bar (not the menu bar) to restore its position. Not a major problem by any means, just a very slight irritation in an otherwise really good package.

**Comment by FlKo** [comment]
Thanks for reporting this issue. Unfortunately I don't have a Mac so I won't be able to reproduce this, but I think you should save your desktop **once**  after correcting the positions, so you prevent the default desktop from being loaded again.

**Comment by carlca** [comment]
Thanks for the reply. That answer makes sense. I'll try it out.
