### ISSUE TITLE
LazarusDockedDesktop

### ISSUE THREAD

**Issue by jcmontherock** [FlKo/LazarusDockedDesktops#4]
It seems not working with the new Lazarus v2 rc1: import StudioPlus xml files has no effects.

**Comment by Xor-el** [comment]
@jcmontherock , did you rebuild/restart the IDE?
It seems to work fine for me.

**Comment by jcmontherock** [comment]
Hello FlKo,
I reinstall Lazarus v2Rc1 as main installation (before it was as secondary installation) and it do not change: when I try to import StudioPlusComplete.xml nothing happend. My computer run Windows10. Docked desktop was running fine with 1.84/3.0.4 version.

**Comment by jcmontherock** [comment]
Same problem with V2 Rc2...

**Comment by jcmontherock** [comment]
I closed it with a wrong choice !.... So I reopen it   :O)

**Comment by Xor-el** [comment]
@jcmontherock , just installed Lazarus v2.0RC2 and everything still works smoothly for me.
Using Windows 10.

**Comment by jcmontherock** [comment]
Finally I found: I made a mistake: I install "AnchorDocking" instead "AnchorDockingDsgn". Now it's ok. Thanks for your answers.

**Comment by Xor-el** [comment]
Glad you finally resolved the issue.
