### ISSUE TITLE
chmreader.pas(80,12) Fatal: Can't find unit chmreader used by ChmLangRef

### ISSUE THREAD

**Issue by eraldguri** [FlKo/LazarusDockedDesktops#5]
I have this error when I try to install sparta_DockedFormEditor, on windows and also linux

**Comment by salvadorbs** [comment]
It is a known issue https://bugs.freepascal.org/view.php?id=35721.you have two solution:
- if you use Lazarus 2.0.1.0 with fpc 3.2.0, you can remove Sparta generics as requirement from Sparta packages (Sparta mdi, i guess)
- more simple, you can remove package chmhelppkg in lazarus and rebuild the ide

**Comment by eraldguri** [comment]
Thank you, it worked
